language: java

git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  
before_script: cd "Simple Marauroa Parent"

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
